---
title: ""
geometry: "left=0.8cm,right=0.5cm,top=1cm,bottom=1cm"
fontsize: 11pt
output:
  pdf_document
---

```{r setup, include=FALSE}
require(wadeR)
require(xtable)
options(xtable.comment = FALSE)
```

###Reference date: `r Sys.Date()`

```{r nests, echo=FALSE, message=FALSE, warning=FALSE,results='asis'}
n = NESTS()# [species == 'REPH']
n = n[, .(nest, state = nest_state, lastCheck, iniClutch, clutch, MSR, IN, m_sure, f_sure)]
n[nest == 'R802', m_sure := 'W,R|W']
n[nest == 'R501', m_sure := 'O,O|Y']
CA = c('R201', 'R901', 'R902', 'R1201', 'R602', 'R603', 'R801', 'R703')
n[nest %in% CA, CA := CA]
n[!is.na(CA), CA := 'CA']
n[nest %like% 'REPH', Rick := TRUE]
n = n[is.na(Rick)]
n[, Rick := NULL]

n[state == 'P', m_sure := '----']

# exclude closed nests
closed = c('R202', 'R204', 'R205', 'R605', 'R701', 'R803', 'R804', 'R904', 'R909', 'R1201', 'R801', 'R902',
           'R302', 'R303', 'R304', 'R601', 'R805', 'R807', 'R808', 'R810',
           'R501', 'R502', 'R802', 'R812', 'R201', 'R602', 'R901', 'P301', 'P603', 'P801',
           'P1201', 'P302', 'P303', 'P304', 'P604', 'R401')
n[nest %in% closed, closed := TRUE]
n = n[is.na(closed)]
n[, closed := NULL]

setorder(n, CA, nest)


x = xtable(n, auto = TRUE, caption = NULL, floating = TRUE, floating.environment = "sidewaystable", latex.environments = "" )

print(x, hline.after = 0:nrow(x))

```






